name: undiyal
description: A student-focused personal finance app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  flutter_notification_listener: ^1.4.0
  flutter_local_notifications: ^19.5.0
  google_fonts: ^6.2.1
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.2.5
  local_auth: ^2.2.0
  home_widget: ^0.9.0
  flutter_dotenv: ^6.0.0
  flutter_sms_inbox: ^1.0.4
  http: ^1.1.0
  google_generative_ai: ^0.4.7
  syncfusion_flutter_datepicker: ^31.1.19
  # flutter_background_service: ^2.0.0
  # flutter_background_service_android: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
